import type { Metadata } from "next";
import { Sacramento, Bellota_Text } from "next/font/google";
import "./globals.css";
import { getFolders } from "@/lib/api/getFolders";

const bellotaText = Bellota_Text({
  variable: "--font-bellota-text",
  weight: ["300", "400", "700"]
});

const sacramento = Sacramento({
  variable: "--font-sacramento",
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await getFolders();

  return (
    <html lang="en">
      <body className={`${bellotaText.variable} ${sacramento.variable}`}>
        {children}
      </body>
    </html>
  );
}
